### ISSUE TITLE
Copy tabs per tab group

### ISSUE THREAD

**Issue by Keith94** [joshdick/tabclip#1]
Because [tabHide](https://bugzilla.mozilla.org/show_bug.cgi?id=1423725) support landed and tabs can be categorized into groups (see [Simple Tab Groups (experimental)](https://github.com/Drive4ik/simple-tab-groups)), it would be nice to copy tabs in current tab group only. Do you know if there's a way to do it?

**Comment by joshdick** [comment]
I don't see anything specifically about tab groups in Mozilla's [WebExtensions API documentation for tabs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs). Although `tabs.hide()` could be potentially used to implement groups, it seems like there's no real way to query for those groups, since it would be up to the extension doing the hiding to maintain groupings/keep track of what's in a group, which wouldn't be visible to other extensions.

Also, `tabs.hide()` is available is a Firefox-specific experimental API. The fact that `tabs.hide()` is only available in Firefox is kind of a nonstarter for this extension because I'd like it to behave the same way and support the same functionality in both Firefox and Chrome.

Thanks for the suggestion though!

**Comment by Keith94** [comment]
As far as I know, the various "tab groups" extensions use the "[Hide Tab](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/hide)" API to hide/show tabs. You might be able to check whether tabs have a "hidden" property and take that into account when querying which tabs to copy. Some tab sidebar extensions like Tab Center Redux [support tab hiding](https://github.com/eoger/tabcenter-redux/commit/ef7b368ca596c7bb61dcc967508c9212af35076d) by displaying only the non-hidden ones.

**Comment by joshdick** [comment]
Like I said:

>  it would be up to the extension doing the hiding to maintain groupings/keep track of what's in a group, which wouldn't be visible to other extensions.

So, I think I'd only be able to query for "tabs that are visible"/"tabs that are hidden", and not any groups more granular than that.

**Comment by Keith94** [comment]
Oh I see what you mean now. Well that is essentially the solution I was looking for: copying current group of visible tabs only.

But I leave it up to you.

**Comment by joshdick** [comment]
Gotcha.

Because tab hiding is not supported in Chrome, and because the Firefox and Chrome versions of this extension are built from the same code, it would be easier for me to maintain this extension without adding Firefox-only features.

I will reconsider if tab hiding is ever added to Chrome.
